/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/KWB5fvQ7Dce
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

import { BoxIcon } from "./icons/box";

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function EmptyCourse() {
  return (
    <div className="flex flex-col items-center justify-center h-[50vh] gap-4">
      <BoxIcon className="h-16 w-16 text-muted" />
      <div className="space-y-2 text-center">
        <h3 className="text-2xl font-semibold">No course available yet.</h3>
        <p className="text-muted-foreground">We update content weekly, please check back later. </p>
      </div>
    </div>
  )
}
