/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Y7EiG3Omz7W
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Progress } from "@/components/ui/progress"

export function Steps() {
  return (
    <Card className="w-full max-w-md">
      <CardHeader>
        <CardTitle>Steps</CardTitle>
        <CardDescription>Complete the following steps to finish this lesson.</CardDescription>
      </CardHeader>
      <CardContent>
        <div className="space-y-4">
          <div className="flex items-start gap-4">
            <div className="flex h-8 w-8 items-center justify-center rounded-full bg-primary text-primary-foreground">
              <CheckIcon className="h-5 w-5" />
            </div>
            <div className="flex-1">
              <div className="flex items-center justify-between">
                <h4 className="font-medium">Create Account</h4>
              </div>
              <p className="text-muted-foreground">Fill out the registration form to create your account.</p>
              <div className="flex gap-2 mt-2">
                <Button variant="outline" size="sm" className="bg-primary text-primary-foreground">
                  Mark as Completed
                </Button>
                <Button variant="outline" size="sm">
                  Execute Test
                </Button>
              </div>
            </div>
          </div>
          <div className="flex items-start gap-4">
            <div className="flex h-8 w-8 items-center justify-center rounded-full bg-primary text-primary-foreground">
              2
            </div>
            <div className="flex-1">
              <div className="flex items-center justify-between">
                <h4 className="font-medium">Verify Email</h4>
              </div>
              <p className="text-muted-foreground">
                Check your inbox for the verification email and click the link to confirm your email address.
              </p>
              <div className="flex gap-2 mt-2">
                <Button variant="outline" size="sm">
                  Mark as Completed
                </Button>
                <Button variant="outline" size="sm">
                  Execute Test
                </Button>
              </div>
            </div>
          </div>
          <div className="flex items-start gap-4">
            <div className="flex h-8 w-8 items-center justify-center rounded-full bg-muted text-muted-foreground hover:bg-primary hover:text-primary-foreground">
              3
            </div>
            <div className="flex-1">
              <div className="flex items-center justify-between">
                <h4 className="font-medium">Set Password</h4>
              </div>
              <p className="text-muted-foreground">Choose a secure password to protect your account.</p>
              <div className="flex gap-2 mt-2">
                <Button variant="outline" size="sm">
                  Mark as Completed
                </Button>
                <Button variant="outline" size="sm">
                  Execute Test
                </Button>
              </div>
            </div>
          </div>
          <div className="flex items-start gap-4">
            <div className="flex h-8 w-8 items-center justify-center rounded-full bg-muted text-muted-foreground hover:bg-primary hover:text-primary-foreground">
              <CheckIcon className="h-5 w-5" />
            </div>
            <div className="flex-1">
              <div className="flex items-center justify-between">
                <h4 className="font-medium">Connect to GitHub</h4>
              </div>
              <p className="text-muted-foreground">Link your GitHub account to enable single sign-on.</p>
              <div className="flex gap-2 mt-2">
                <Button variant="outline" size="sm">
                  Mark as Completed
                </Button>
                <Button variant="outline" size="sm">
                  Execute Test
                </Button>
              </div>
            </div>
          </div>
        </div>
        <div className="mt-6 flex w-full">
          <Progress value={75} className="w-full" />
        </div>
      </CardContent>
    </Card>
  )
}

function CheckIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 6 9 17l-5-5" />
    </svg>
  )
}
