/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/5hCrWCnal6Z
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client";

import { useState } from "react";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Label } from "@/components/ui/label";
import {
  Card,
  CardHeader,
  CardTitle,
  CardContent,
  CardFooter,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import Link from "next/link";

export function Pricing() {
  const [isAnnual, setIsAnnual] = useState(false);

  const [pricing, setPricing] = useState([
    {
      title: "Free",
      cost: 0,
      modules: [
        {
          title: "Best practices",
          meta: {
            courses: 8,
            chapters: 24,
            lessons: 45,
            challenges: 65,
            tests: 75,
          },
        },
      ],
    },
    {
      title: "Pro",
      cost: 0,
      modules: [],
    },
    {
      title: "Team",
      cost: 0,
      modules: [],
    },
    {
      title: "Lifetime access",
      cost: 0,
      modules: [],
    },
  ]);

  return (
    <div className="w-full max-w-6xl mx-auto py-12 md:py-16 lg:py-20">
      <div className="grid gap-8 md:gap-12">
        <div className="text-center">
          <h2 className="text-3xl md:text-4xl font-bold">Pricing</h2>
          <p className="text-muted-foreground mt-2 max-w-md mx-auto">
            Choose the plan that fits your needs.
          </p>
        </div>
        {/* <div className="flex items-center justify-center gap-4">
          <span className="text-sm font-medium">Monthly</span>
          <RadioGroup
            value=""
            onValueChange={(value) => setIsAnnual(0)}
            className="flex items-center gap-2"
          >
            <RadioGroupItem id="annual" value className="peer sr-only" />
            <Label
              htmlFor="annual"
              className="w-12 h-6 bg-muted rounded-full relative cursor-pointer peer-checked:bg-primary transition-colors"
            >
              <span className="absolute w-5 h-5 bg-card rounded-full top-1/2 -translate-y-1/2 left-1 peer-checked:translate-x-5 transition-transform" />
            </Label>
            <span className="text-sm font-medium">Annual</span>
          </RadioGroup>
        </div> */}
        <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">
          {pricing.map((tier, index) => (
            <Card className="p-6 border-2 border-muted rounded-lg" key={index}>
              <CardHeader>
                <CardTitle>{tier?.title}</CardTitle>
              </CardHeader>
              <CardContent>
                {tier.modules.length > 0 && (
                  <div className="text-4xl font-bold">
                    ${isAnnual ? tier?.cost * 12 : tier?.cost}
                    <span className="text-sm font-normal text-muted-foreground">
                      /mo
                    </span>
                  </div>
                )}
                {!tier.modules.length ? (
                  <Button variant="default" className="w-full mt-4">
                    Coming soon
                  </Button>
                ) : (
                  <Link href="https://app.tthroo.com/">
                    <Button variant="default" className="w-full mt-4">
                      Get Started
                    </Button>
                  </Link>
                )}
                {tier?.modules.map((module) => (
                  <>
                    <div className="font-medium mt-4">{module.title}</div>
                    <ul className="space-y-2 mt-4 text-sm">
                      <li>
                        <CheckIcon className="w-4 h-4 mr-2 inline-block text-primary" />
                        {module.meta.courses} courses
                      </li>
                      <li>
                        <CheckIcon className="w-4 h-4 mr-2 inline-block text-primary" />
                        {module.meta.chapters} chapters
                      </li>
                      <li>
                        <CheckIcon className="w-4 h-4 mr-2 inline-block text-primary" />
                        {module.meta.lessons} lessons
                      </li>
                      <li>
                        <CheckIcon className="w-4 h-4 mr-2 inline-block text-primary" />
                        {module.meta.challenges} challenges
                      </li>
                      <li>
                        <CheckIcon className="w-4 h-4 mr-2 inline-block text-primary" />
                        {module.meta.tests} tests
                      </li>
                    </ul>
                  </>
                ))}
              </CardContent>
              {/* <CardFooter>
                
              </CardFooter> */}
            </Card>
          ))}
        </div>
      </div>
    </div>
  );
}

function CheckIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 6 9 17l-5-5" />
    </svg>
  );
}
